app/models/celador.py
from app import db
from flask_login import UserMixin

class Celador(db.Model, UserMixin):
    __tablename__= "celador"
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(255), nullable=False)
    cedula = db.Column(db.String(255), nullable=False)
    correo = db.Column(db.String(255), nullable=False)
    contra = db.Column(db.String(255), nullable=False)

app/routes/celador_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.celador import Celador
from app import db
from flask_bcrypt import Bcrypt

bp = Blueprint('celador', __name__)

@bp.route('/Celador')
def index():
    data = Celador.query.all()
    return render_template('celador/index.html', data=data)

@bp.route('/Celador/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombre = request.form['nombre']
        cedula = request.form['cedula']
        correo =  request.form['correo']
        contra =  request.form['contra']
        bcrypt = Bcrypt()
        
        password =bcrypt.generate_password_hash(contra).decode('utf-8')
        
        new_celador = Celador(nombre=nombre, cedula=cedula, correo=correo, contra=password)
        db.session.add(new_celador)
        db.session.commit()
        
        return redirect(url_for('celador.index'))

    return render_template('celador/add.html')

@bp.route('/Celador/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    celador = Celador.query.get_or_404(id)

    if request.method == 'POST':
        celador.nombre = request.form['nombre']
        celador.cedula = request.form['cedula']
        celador.correo = request.form['correo']
        db.session.commit()
        return redirect(url_for('celador.index'))

    return render_template('celador/edit.html', celador=celador)

@bp.route('/Celador/delete/<int:id>')
def delete(id):
    celador = Celador.query.get_or_404(id)
    
    db.session.delete(celador)
    db.session.commit()

    return redirect(url_for('celador.index'))

app/templates/celador/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar Celador</title>
    <style>
        .container {
            width: 400px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <div class="container">
    <h1 style="text-align: center;">Agregar Celador</h1>
    <form action="{{ url_for('celador.add') }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required>
        <label for="cedula">Cedula:</label>
        <input type="text" id="cedula" name="cedula" required>
        <label for="correo">Correo:</label>
        <input type="text" id="correo" name="correo" required>
        <label for="contra">Contraseña:</label>
        <input type="password" id="contra" name="contra" required>
        <button type="submit">Agregar Celador</button>
        <a href="{{ url_for('celador.index') }}">Volver</a>
    </form>
    </div>
</body>
</html>

app/templates/celador/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Celadores</title>
    <style>
        .container {
            width: 400px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <div class="container">
    <h1 style="text-align: center;">Editar Celadores</h1>
    <form action="{{ url_for('celador.edit', id=celador.id) }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" value="{{ celador.nombre }}" required>
        <label for="cedula">Cedula:</label>
        <input type="text" id="cedula" name="cedula" value="{{ celador.cedula }}" required>
        <label for="correo">Correo:</label>
        <input type="text" id="correo" name="correo" value="{{ celador.correo }}" required>
        <button type="submit">Actualizar Celador</button>
        <a href="{{ url_for('celador.index') }}">Volver</a>
    </form>
    </div>
</body>
</html>

app/templates/celador/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Celador</title>
    <style> 
        .menu ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }
        
        .menu ul li {
            float: left;
        }
        
        .menu ul li a {
            display: block;
            color: rgb(31, 104, 31);
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        
        .menu ul li a:hover {
            background-color: #1dad01ce;
        }

        .container {
            width: 80%;
            margin: 20px auto;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            padding: 20px;
        }

        .background {
            background-color: white;
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="container background">
    <h1 style="text-align: center;">Lista de Celadores</h1>
    <div style="margin: 28px auto;">
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Cedula</th>
            <th>Correo</th>
            <th>Contraseña</th>
            <th>Acciones</th>
        </tr>
        {% for celador in data %}
            <tr>
                <td>{{ celador.id }}</td>
                <td>{{ celador.nombre }}</td>
                <td>{{ celador.cedula }}</td>
                <td>{{ celador.correo }}</td>
                <td>{{ celador.contra }}</td>
                <td>
                    <a href="{{ url_for('celador.edit', id=celador.id) }}">Editar</a>
                    <a href="{{ url_for('celador.delete', id=celador.id) }}">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
        {% endfor %}
    </table>
    <nav class="menu">
        <ul>
            <li><a href="{{ url_for('celador.add') }}">Agregar Celador</a></li>
            <li><a href="{{ url_for('login.login') }}">Iniciar sesion</a></li>
        </ul>
    </nav>
    </div>
    </div>
</body>
</html>