app/models/aprendiz.py
from app import db

class Aprendiz(db.Model):
    __tablename__ = "aprendiz"
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(255), nullable=False)
    ficha = db.Column(db.String(255), nullable=False)
    cedula = db.Column(db.String(255), nullable=False)

app/routes/aprendiz_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.aprendiz import Aprendiz
from app import db

bp = Blueprint('aprendiz', __name__)

@bp.route('/Aprendiz')
def index():
    data = Aprendiz.query.all()
    return render_template('aprendiz/index.html', data=data)

@bp.route('/Aprendiz/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombre = request.form['nombre']
        ficha = request.form['ficha']
        cedula = request.form['cedula']
        
        new_aprendiz = Aprendiz(nombre=nombre, ficha=ficha, cedula=cedula)
        db.session.add(new_aprendiz)
        db.session.commit()
        
        return redirect(url_for('aprendiz.index'))

    return render_template('aprendiz/add.html')

@bp.route('/Aprendiz/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    aprendiz = Aprendiz.query.get_or_404(id)

    if request.method == 'POST':
        aprendiz.nombre = request.form['nombre']
        aprendiz.ficha = request.form['ficha']
        aprendiz.cedula = request.form['cedula']
        db.session.commit()
        return redirect(url_for('aprendiz.index'))

    return render_template('aprendiz/edit.html', aprendiz=aprendiz)

@bp.route('/Aprendiz/delete/<int:id>')
def delete(id):
    aprendiz = Aprendiz.query.get_or_404(id)
    
    db.session.delete(aprendiz)
    db.session.commit()

    return redirect(url_for('aprendiz.index'))

@bp.route('/Aprendiz/buscar', methods=['GET'])
def buscar():
    nombre = request.args.get('nombre')
    data = Aprendiz.query.filter(Aprendiz.nombre.like(f"%{nombre}%")).all()
    print(data)
    return render_template('aprendiz/index.html',data=data)

app/templates/aprendiz/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar Aprendiz</title>
    <style>
        .container {
            width: 400px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <div class="container">
    <h1 style="text-align: center;">Agregar Aprendiz</h1>
    <form action="{{ url_for('aprendiz.add') }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required>
        <label for="ficha">Ficha:</label>
        <input type="text" id="ficha" name="ficha" required>
        <label for="cedula">Cedula:</label>
        <input type="text" id="cedula" name="cedula" required>
        <button type="submit">Agregar Aprendiz</button>
        <a href="{{ url_for('aprendiz.index') }}">Volver</a>
    </form>
    </div>
</body>
</html>

app/templates/aprendiz/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Aprendiz</title>
    <style>
        .container {
            width: 400px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <div class="container">
    <h1>Editar Aprendiz</h1>
    <form action="{{ url_for('aprendiz.edit', id=aprendiz.id) }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" value="{{ aprendiz.nombre }}" required>
        <label for="ficha">Ficha:</label>
        <input type="text" id="ficha" name="ficha" value="{{ aprendiz.ficha }}" required>
        <label for="cedula">Cedula:</label>
        <input type="text" id="cedula" name="cedula" value="{{ aprendiz.cedula }}" required>
        <button type="submit">Actualizar Aprendiz</button>
        <a href="{{ url_for('aprendiz.index') }}">Volver</a>
    </form>
    </div>
</body>
</html>

app/templates/aprendiz/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Aprendiz</title>
    <style> 
        .menu ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }
        
        .menu ul li {
            float: left;
        }
        
        .menu ul li a {
            display: block;
            color: rgb(31, 104, 31);
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        
        .menu ul li a:hover {
            background-color: #1dad01ce;
        }

        .container {
            width: 80%;
            margin: 20px auto;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            padding: 20px;
        }

        .background {
            background-color: white;
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="container background">
    <h1 style="text-align: center;">Lista de Aprendices</h1>
    <form action="{{ url_for('aprendiz.buscar', nombre=nAprendiz)}}" method="get">
        <div class="form-group">
            <label for="nombre">Nombre Aprendiz</label>
            <input type="text" id="nombre" name="nombre">
        </div>
        <div>
            <button type="submit">Buscar</button>
        </div>
    </form>
    <div style="margin: 28px auto;">
        <table>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Ficha</th>
                <th>Cedula</th>
                <th>Acciones</th>
            </tr>
            {% for aprendiz in data %}
                <tr>
                    <td>{{ aprendiz.id }}</td>
                    <td>{{ aprendiz.nombre }}</td>
                    <td>{{ aprendiz.ficha }}</td>
                    <td>{{ aprendiz.cedula }}</td>
                    <td>
                        <a href="{{ url_for('aprendiz.edit', id=aprendiz.id) }}">Editar</a>
                        <a href="{{ url_for('aprendiz.delete', id=aprendiz.id) }}">Eliminar</a>
                        <!-- Agrega aquí el enlace para eliminar -->
                    </td>
                </tr>
            {% endfor %}
        </table>
        <nav class="menu">
            <ul>
                <li><a href="{{ url_for('aprendiz.add') }}">Agregar Aprendiz</a></li>
                <li><a href="{{ url_for('entrada.index') }}">Ir a Entrada</a></li>
            </ul>
        </nav>
    </div>
    </div>
</body>
</html>