app/models/entrada.py
from app import db
from datetime import datetime

class Entrada(db.Model):
    __tablename__= "entrada"
    id = db.Column(db.Integer, primary_key=True)
    fechaE = db.Column(db.TIMESTAMP, nullable=True)
    fechaS = db.Column(db.TIMESTAMP, nullable=True)
    aprendiz = db.Column(db.Integer, db.ForeignKey('aprendiz.id'))
    modelo_aprendiz = db.relationship('Aprendiz', backref='tus_modelos')
    portatil = db.Column(db.Integer, db.ForeignKey('portatil.id'))
    modelo_portatil = db.relationship('Portatil', backref='tus_modelos')

app/routes/entrada_routes.py
from datetime import datetime       
from sqlalchemy import func
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models.entrada import Entrada
from app.models.aprendiz import Aprendiz
from app.models.portatil import Portatil
from app import db

bp = Blueprint('entrada', __name__)

@bp.route('/Entrada')
def index():
    data = Entrada.query.all()
    return render_template('entrada/index.html', data=data)

@bp.route('/Entrada/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        aprendiz = request.form['nombreAprendiz']
        portatil = request.form['idPortatil']
        
        consulta = Aprendiz.query.filter_by(nombre=aprendiz).first()
        consulta1 = Portatil.query.filter_by(id=portatil).first()
        if not consulta:    
            flash('Aprendiz no encontrado')
        elif not consulta1: 
            flash('Portatil no encontrado')
        elif consulta and consulta1:
            new_entrada = Entrada(fechaE=func.now(), aprendiz=consulta.id, portatil=portatil)
            db.session.add(new_entrada)
            db.session.commit()
            return redirect(url_for('entrada.index'))
        
    aprendices = Aprendiz.query.all()
    return render_template('entrada/add.html', aprendices=aprendices)

@bp.route('/Entrada/delete/<int:id>')
def delete(id):
    entrada = Entrada.query.get_or_404(id)
    
    db.session.delete(entrada)
    db.session.commit()

    return redirect(url_for('entrada.index'))

@bp.route('/Entrada/exit/<int:id>', methods=['GET', 'POST'])
def exit(id):
    entrada = Entrada.query.get_or_404(id)


    if request.method == 'GET':
        entrada.fechaS = func.now()
        db.session.commit()
        return redirect(url_for('entrada.index'))

    return redirect(url_for('entrada.index'))


@bp.route('/Entrada/buscar', methods=['GET'])
def buscar():
    nombre = request.args.get('nombre')
    print("Nombre a buscar ",nombre)
    data = Entrada.query.join(Aprendiz).filter(Aprendiz.nombre.like(f"%{nombre}%")).all()
    return render_template('entrada/index.html',data=data)

app/routes/login_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from flask_bcrypt import Bcrypt
from app.models.celador import Celador

login_bp = Blueprint('login', __name__)

@login_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        correo = request.form['correo']
        contra = request.form['contra']
        
        user = Celador.query.filter_by(correo=correo).first()
        bcrypt = Bcrypt()
        
        if user and bcrypt.check_password_hash(user.contra,contra):
            login_user(user)
            return redirect(url_for('login.dashboard'))
        flash('Correo o contraseña incorrecta. Vuelva a ingresar los datos', 'danger')
    
    if current_user.is_authenticated:
        return redirect(url_for('login.dashboard'))
    return render_template("login/login.html")

@login_bp.route('/dashboard')
@login_required
def dashboard():
    return redirect(url_for('entrada.index'))

@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('login.login'))

app/templates/entrada/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar Entrada</title>
    <style>
        .container {
            width: 400px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    {%with mensajes = get_flashed_messages(with_categories=true) %}
        {%for categoria, mensaje in mensajes %}
            <script>
                window.onload = function(){
                    window.setTimeout(function(){
                        alert("{{mensaje}}");
                    }, 500);
                };
            </script>
        {%endfor%}
    {%endwith%}
    <div class="container">     
    <h1 style="text-align: center;">Agregar Entrada</h1>
    <form action="{{ url_for('entrada.add') }}" method="post">
        <label for="idAprendiz">Aprendiz:</label>
        <input type="text" id="idAprendiz" name="nombreAprendiz" list="bAprendiz" autocomplete="off">
        <label for="idPortatil">Portatil:</label>
        <input type="text" id="idPortatil" name="idPortatil" required>
        <button type="submit">Agregar Entrada</button>
        <a href="{{ url_for('entrada.index') }}">Volver</a>
    </form>
    </div>

    <dataList id="bAprendiz">
        {%for aprendiz in aprendices %}
            <option value="{{aprendiz.nombre}}"></option>
        {%endfor%}
    </dataList>
</body>
</html>

app/templates/entrada/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Entrada</title>
    <style>
        .menu ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }

        .menu ul li {
            float: left;
        }

        .menu ul li a {
            display: block;
            color: rgb(31, 104, 31);
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .menu ul li a:hover {
            background-color: #1dad01ce;
        }

        .oculto {
            display: none;
        }

        .container {
            width: 80%;
            margin: 20px auto;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            padding: 20px;
        }

        .background {
            background-color: white;
            padding: 20px;
        }
    </style>
</head>

<body>
    <div class="container background">
    <div style="text-align: center;">
        <h1>Lista de Entradas</h1>
        <h2>{{current_user.nombre}}</h2>
    </div>
    <form action="{{ url_for('entrada.buscar', nombre=nAprendiz)}}" method="get">
        <div class="form-group">
            <label for="nombre">Nombre Aprendiz</label>
            <input type="text" id="nombre" name="nombre">
        </div>
        <div>
            <button type="submit">Buscar</button>
        </div>
    </form>
    <div style="margin: 28px auto;">
        <table>
            <tr>
                <th>Hora Entrada</th>
                <th>Hora Salida</th>
                <th>Aprendiz</th>
                <th>Portatil</th>
                <th>Acciones</th>
            </tr>
            {% for entrada in data %}
            <tr>
                <td>{{ entrada.fechaE }}</td>
                <td>{{ entrada.fechaS }}</td>
                <td>{{ entrada.modelo_aprendiz.nombre }}</td>
                <td>{{ entrada.modelo_portatil.nombre }} {{ entrada.modelo_portatil.color }}</td>
                <td>
                    {% if entrada.fechaS is none or entrada.fechaS  == '' %}
                    <a href="{{ url_for('entrada.exit', id=entrada.id) }}">Salida</a>
                    {% endif %}
                    <a href="{{ url_for('entrada.delete', id=entrada.id) }}">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
            {% endfor %}
        </table>
        <nav class="menu">
            <ul>
                <li><a href="{{ url_for('entrada.add') }}">Agregar Entrada</a></li>
                <li><a href="{{ url_for('aprendiz.index') }}">Agregar Aprendiz</a></li>
                <li><a href="{{ url_for('portatil.index') }}">Agregar Portatil</a></li>
                <li><a href="{{ url_for('login.logout') }}">Cerrar sesion</a></li>
            </ul>
        </nav>
    </div>
    </div>
</body>

</html>